apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-name
    version: v1
  name: app-name
  namespace: default

spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: app-name
  template:
    metadata:
      labels:
        app: app-name
        version: v1
    spec:
      containers:
      - image: kate/app-name
        imagePullPolicy: IfNotPresent
        name: app-name
        resources:
          requests:
            cpu: 100m
            memory: 112Mi
          limits:
            cpu: 200m
            memory: 224Mi

      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-name
  name: app-name
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-name
  sessionAffinity: None
  type: LoadBalancer